name: Deploy to Pinata

on:
    push:
      branches:
        - main

jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Deploy to Pinata
          uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
          with:
            pin-name: 'MonSiteWeb'
            path: './'
            pinata-api-key: ${{ secrets.PINATA_API_KEY }}
            pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
            verbose: true
            remove-old: false
  
        - name: Get the output hash
          run: echo "Le CID est ${{ steps.deploy.outputs.hash }}"
  
