name: Deploy to Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install IPFS
        run: |
          wget https://dist.ipfs.io/go-ipfs/v0.12.1/go-ipfs_v0.12.1_linux-amd64.tar.gz
          tar xvfz go-ipfs_v0.12.1_linux-amd64.tar.gz
          sudo mv go-ipfs/ipfs /usr/local/bin/ipfs

      - name: Initialize IPFS
        run: |
          ipfs init

      - name: Start IPFS daemon
        run: |
          ipfs daemon --init &
          sleep 5  # Attendre quelques secondes pour que le démon IPFS démarre complètement

      - name: Deploy to Pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'MonSiteWeb'
          path: './'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
          verbose: true
          remove-old: false

      - name: Get the output hash
        run: |
          cid=$(ipfs add -Q -r ./)
          echo "Le CID est $cid"
